In [16]:
import pandas as pd
from pathlib import Path

caminho = Path(r"C:\Users\Felipe\Documents\Python\Clusterizacao_Municipios\dados")

atlas = pd.read_excel(caminho / "brutos" / "Atlas_BR_Municipios.xlsx")

display(atlas.head())
display(atlas.shape)
display(atlas.info())

,Territorialidade,Posição IDHM,IDHM,Posição IDHM Renda,IDHM Renda,Posição IDHM Educação,IDHM Educação,Posição IDHM Longevidade,IDHM Longevidade
0,São Caetano do Sul (SP),1,0.862,1,0.891,2,0.811,19,0.887
1,Águas de São Pedro (SP),2,0.854,12,0.849,1,0.825,11,0.890
2,Florianópolis (SC),3,0.847,5,0.870,5,0.800,147,0.873
3,Vitória (ES),4,0.845,3,0.876,4,0.805,551,0.855
4,Balneário Camboriú (SC),4,0.845,10,0.854,6,0.789,1,0.894

(5565, 9)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5565 entries, 0 to 5564
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Territorialidade          5565 non-null   object
 1   Posição IDHM              5565 non-null   int64
 2   IDHM                      5565 non-null   float64
 3   Posição IDHM Renda        5565 non-null   int64
 4   IDHM Renda                5565 non-null   float64
 5   Posição IDHM Educação     5565 non-null   int64
 6   IDHM Educação             5565 non-null   float64
 7   Posição IDHM Longevidade  5565 non-null   int64
 8   IDHM Longevidade          5565 non-null   float64
dtypes: float64(4), int64(4), object(1)
memory usage: 391.4+ KB

None

In [17]:
display(atlas['Territorialidade'].head(10))

0    São Caetano do Sul (SP)
1    Águas de São Pedro (SP)
2         Florianópolis (SC)
3               Vitória (ES)
4    Balneário Camboriú (SC)
5                Santos (SP)
6               Niterói (RJ)
7               Joaçaba (SC)
8              Brasília (DF)
9              Curitiba (PR)
Name: Territorialidade, dtype: object

In [18]:
atlas = atlas.drop(columns=[col for col in atlas.columns if "Posição" in col])
display(atlas.columns)

Index(['Territorialidade', 'IDHM', 'IDHM Renda', 'IDHM Educação',
       'IDHM Longevidade'],
      dtype='object')

In [19]:
atlas = atlas.rename(columns={'Territorialidade': 'municipio'})
display(atlas.head(10))

                 municipio   IDHM  IDHM Renda  IDHM Educação  IDHM Longevidade
0  São Caetano do Sul (SP)  0.862       0.891          0.811             0.887
1  Águas de São Pedro (SP)  0.854       0.849          0.825             0.890
2       Florianópolis (SC)  0.847       0.870          0.800             0.873
3             Vitória (ES)  0.845       0.876          0.805             0.855
4  Balneário Camboriú (SC)  0.845       0.854          0.789             0.894
5              Santos (SP)  0.840       0.861          0.807             0.852
6             Niterói (RJ)  0.837       0.887          0.773             0.854
7             Joaçaba (SC)  0.827       0.823          0.771             0.891
8            Brasília (DF)  0.824       0.863          0.742             0.873
9            Curitiba (PR)  0.823       0.850          0.768             0.855

In [20]:
atlas['municipio_sidra'] = atlas['municipio'].str.replace(' (', ' - ', regex=False).str.replace(')', '', regex=False)

display(atlas.head(10))

,municipio,IDHM,IDHM Renda,IDHM Educação,IDHM Longevidade,municipio_sidra
0,São Caetano do Sul (SP),0.862,0.891,0.811,0.887,São Caetano do Sul - SP
1,Águas de São Pedro (SP),0.854,0.849,0.825,0.890,Águas de São Pedro - SP
2,Florianópolis (SC),0.847,0.870,0.800,0.873,Florianópolis - SC
3,Vitória (ES),0.845,0.876,0.805,0.855,Vitória - ES
4,Balneário Camboriú (SC),0.845,0.854,0.789,0.894,Balneário Camboriú - SC
5,Santos (SP),0.840,0.861,0.807,0.852,Santos - SP
6,Niterói (RJ),0.837,0.887,0.773,0.854,Niterói - RJ
7,Joaçaba (SC),0.827,0.823,0.771,0.891,Joaçaba - SC
8,Brasília (DF),0.824,0.863,0.742,0.873,Brasília - DF
9,Curitiba (PR),0.823,0.850,0.768,0.855,Curitiba - PR

In [21]:
atlas.to_csv(caminho / 'processados' / 'Atlas_tratado.csv', index=False)

Fim!